# 
# dependency manager - yarn
#   about:
#     - http://yarnpkg.com/en/docs/cli
#   notes:
#     - package.json must include "test": "CI=true react-scripts test --env=jsdom",
#        or yarn test will hang
#         

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# restore dependencies and project specific tool via NuGet
#- script: dotnet restore
#  displayName: 'Script: dotnet restore'

- script: cd ClientApp && yarn install
  displayName: 'Script: yarn install'

- script: cd ClientApp && yarn test --ci
  displayName: 'Script: yarn test'