#
# dependency manager - yarn
#   notes:
#     - package.json must include "test": "CI=true react-scripts test --env=jsdom",
#        or yarn test will hang
#

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: "SonarCloudConnection"
      organization: "speedcm"
      scannerMode: "MSBuild"
      projectKey: "xExperiments"

  - script: dotnet restore
    displayName: "Script: dotnet restore"

  - script: dotnet ef database update
    displayName: "Script: dotnet ef database update"

  - task: replacetokens@3
    displayName: "Replace Tokens: Help.tsx"
    inputs:
      targetFiles: "**/Help.tsx"
      encoding: "auto"
      writeBOM: true
      actionOnMissing: "warn"
      keepToken: false
      tokenPrefix: "__"
      tokenSuffix: "__"

  - script: dotnet publish "./hedwig.csproj" --output "./dist" --configuration Release --no-restore
    displayName: "Script: dotnet publish"

  - script: cd ClientApp && yarn test --ci
    displayName: "Script: yarn test"

  - task: SonarCloudAnalyze@1
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: "300"

  - script: cp ./hedwig.db ./dist/hedwig.db
    displayName: "Script: package sqlite db"

  #
  # ISSUE: provider Microsoft.EntityFrameworkCore.Sqlite does not support --idempotent
  #
  #- script: dotnet ef migrations script --output $(Build.ArtifactStagingDirectory)/react-spa-db.sql --context HedwigContext  --idempotent
  #  displayName: 'Script: dotnet ef migrations script'

  - script: dotnet ef migrations script --output $(Build.ArtifactStagingDirectory)/react-spa-db.sql --context HedwigContext
    displayName: "Script: dotnet ef migrations script"

  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)/dist"
      includeRootFolder: false
      archiveType: "zip"
      #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
      archiveFile: "$(Build.ArtifactStagingDirectory)/react-spa.zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts: react-spa"
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)/react-spa.zip"
      artifactName: react-spa

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifacts: react-spa-db"
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)/react-spa-db.sql"
      artifactName: react-spa-db
