# 
# dependency manager - yarn
#   about:
#     - http://yarnpkg.com/en/docs/cli
#   notes:
#     - package.json must include "test": "CI=true react-scripts test --env=jsdom",
#        or yarn test will hang
#         

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# restore dependencies and project specific tool via NuGet
#- script: dotnet restore
#  displayName: 'Script: dotnet restore'

- script: cd ClientApp && yarn install
  displayName: 'Script: yarn install'

- script: cd ClientApp && yarn test --ci
  displayName: 'Script: yarn test'

- script: cd ClientApp && yarn run build
  displayName: 'Script: yarn run build'

- script: cd ClientApp && ls && cd build && ls
  displayName: 'Script: ls'

# Compress files into .7z, .tar.gz, or .zip
- task: ArchiveFiles@2
  displayName: 'Archive Files'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/ClientApp/build' 
    includeRootFolder: false
    archiveType: 'zip'
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/ReactApp.zip' 
    replaceExistingArchive: true 

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/ReactApp.zip'