# 
# dependency manager - yarn
#    - see http://yarnpkg.com/en/docs/cli

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# restore dependencies and project specific tool via NuGet
- script: dotnet restore
  displayName: 'Script: dotnet restore'

# install project dependencies via yarn
- script: cd ClientApp && yarn install
  displayName: 'Script: yarn install'

# perform test via yarn
- script: cd ClientApp && yarn test --ci
  displayName: 'Script: yarn test'